# New ePims Springboot Server
webservices.url=http://localhost:8080

#user info
epims.user=<epimsUser>
epims.pswd=<epimsPassword>

# Define which transfer mode to use
transfer.mode=direct
# If direct, epims.root should be specified
epims.root=<PATH_TO_DEV_ROOT>
# If ftp all following ftp params should be specified

# --- FTP Parameters ---
# FTP info (SFTP mode will is used)
ftp.host=<FTP_HOST>
# FTP port (defaults to 22)
ftp.port=22
#user login to connect to FTP host
ftp.login=<FTP_LOGIN>
#Specify which FTP authentication method to use
# if 'KEY_MODE' ftp.password is ignored and default key or ftp.keyPath specified key is used
# if 'PASSWD_MODE' ftp.password is used and ftp.keyPath is ignored
ftp.auth.mode=key

# Path to the private key used for SFTP authentication.
# Default is ./conf/epims-id_rsa next to the distribution.
# You can use an absolute path if desired.
ftp.keyPath=./conf/epims-id_rsa
ftp.password=<ftp_pass>
